import {
  Zap,
  Thermometer,
  Wrench,
  ShieldCheck,
  Award,
  IndianRupee,
  Target,
  Leaf,
  type LucideIcon,
} from "lucide-react";

export const compareContent = {
  hero: {
    title: "Product Comparison",
    subtitle:
      "Compare our TOPCon and MonoPERC modules side-by-side to find the perfect fit for your project requirements.",
    cta: "Talk to Our Experts",
    ctaRoute: "contact" as const,
  },

  products: {
    topcon: {
      name: "TOPCon 580W",
      series: "Bifacial TOPCon",
      wattage: 580,
      dimensions: "2278 × 1134 × 35 mm",
      weight: "32.5 kg",
      cellType: "N-type TOPCon",
      cellsPerModule: 144,
      efficiency: 22.52,
      temperatureCoefficient: -0.29,
      powerTolerance: "+5W / 0W",
      warranty: "30 years",
      color: "Black / Black",
      certifications: ["IEC 61215", "IEC 61730", "IEC 62941", "BIS", "CE"],
      featureHighlights: [
        "Bifacial technology — up to 30% additional energy yield",
        "Lowest temperature coefficient for hot climate performance",
        "Highest efficiency in its class",
        "Better low-light & shading response",
      ],
    },
    monoperc: {
      name: "MonoPERC 545W",
      series: "Bifacial MonoPERC",
      wattage: 545,
      dimensions: "2278 × 1134 × 35 mm",
      weight: "32.0 kg",
      cellType: "P-type MonoPERC",
      cellsPerModule: 144,
      efficiency: 21.16,
      temperatureCoefficient: -0.35,
      powerTolerance: "+5W / 0W",
      warranty: "25 years",
      color: "Black / Silver",
      certifications: ["IEC 61215", "IEC 61730", "IEC 62941", "BIS", "CE"],
      featureHighlights: [
        "Proven PERC technology with track record of reliability",
        "Lower upfront cost per watt",
        "Excellent performance in moderate climates",
        "Wide availability and faster lead times",
      ],
    },
  },

  comparisonCategories: [
    {
      id: "electrical",
      name: "Electrical Performance",
      icon: Zap as LucideIcon,
      parameters: [
        {
          label: "Maximum Power (Pmax)",
          unit: "W",
          topconValue: 580,
          monopercValue: 545,
          winner: "topcon" as const,
        },
        {
          label: "Open Circuit Voltage (Voc)",
          unit: "V",
          topconValue: 51.87,
          monopercValue: 49.65,
          winner: "topcon" as const,
        },
        {
          label: "Short Circuit Current (Isc)",
          unit: "A",
          topconValue: 14.22,
          monopercValue: 14.01,
          winner: "topcon" as const,
        },
        {
          label: "Voltage at Pmax (Vmp)",
          unit: "V",
          topconValue: 43.56,
          monopercValue: 41.65,
          winner: "topcon" as const,
        },
        {
          label: "Current at Pmax (Imp)",
          unit: "A",
          topconValue: 13.31,
          monopercValue: 13.09,
          winner: "topcon" as const,
        },
        {
          label: "Module Efficiency",
          unit: "%",
          topconValue: 22.52,
          monopercValue: 21.16,
          winner: "topcon" as const,
        },
      ],
    },
    {
      id: "temperature",
      name: "Temperature Performance",
      icon: Thermometer as LucideIcon,
      parameters: [
        {
          label: "Temp Coeff of Pmax",
          unit: "%/°C",
          topconValue: -0.29,
          monopercValue: -0.35,
          winner: "topcon" as const,
        },
        {
          label: "Temp Coeff of Voc",
          unit: "%/°C",
          topconValue: -0.26,
          monopercValue: -0.30,
          winner: "topcon" as const,
        },
        {
          label: "Temp Coeff of Isc",
          unit: "%/°C",
          topconValue: 0.05,
          monopercValue: 0.05,
          winner: "tie" as const,
        },
        {
          label: "NOCT",
          unit: "°C",
          topconValue: 44.2,
          monopercValue: 45.0,
          winner: "topcon" as const,
        },
      ],
    },
    {
      id: "mechanical",
      name: "Mechanical Specifications",
      icon: Wrench as LucideIcon,
      parameters: [
        {
          label: "Dimensions",
          unit: "",
          topconValue: "2278 × 1134 × 35 mm",
          monopercValue: "2278 × 1134 × 35 mm",
          winner: "tie" as const,
        },
        {
          label: "Weight",
          unit: "kg",
          topconValue: 32.5,
          monopercValue: 32.0,
          winner: "monoperc" as const,
        },
        {
          label: "Cell Type",
          unit: "",
          topconValue: "N-type TOPCon",
          monopercValue: "P-type MonoPERC",
          winner: "tie" as const,
        },
        {
          label: "Cells Per Module",
          unit: "",
          topconValue: 144,
          monopercValue: 144,
          winner: "tie" as const,
        },
        {
          label: "Front Glass",
          unit: "",
          topconValue: "3.2 mm AR coated",
          monopercValue: "3.2 mm AR coated",
          winner: "tie" as const,
        },
        {
          label: "Back Sheet",
          unit: "",
          topconValue: "Transparent (bifacial)",
          monopercValue: "Transparent (bifacial)",
          winner: "tie" as const,
        },
        {
          label: "Frame",
          unit: "",
          topconValue: "Anodized aluminium",
          monopercValue: "Anodized aluminium",
          winner: "tie" as const,
        },
        {
          label: "Junction Box",
          unit: "",
          topconValue: "IP68 rated",
          monopercValue: "IP68 rated",
          winner: "tie" as const,
        },
        {
          label: "Cable",
          unit: "",
          topconValue: "1.2 m, 4 mm²",
          monopercValue: "1.2 m, 4 mm²",
          winner: "tie" as const,
        },
      ],
    },
    {
      id: "thermal",
      name: "Thermal Characteristics",
      icon: Thermometer as LucideIcon,
      parameters: [
        {
          label: "Operating Temp Range",
          unit: "°C",
          topconValue: "-40 to +85",
          monopercValue: "-40 to +85",
          winner: "tie" as const,
        },
        {
          label: "Max System Voltage",
          unit: "V",
          topconValue: 1500,
          monopercValue: 1500,
          winner: "tie" as const,
        },
        {
          label: "Max Series Fuse",
          unit: "A",
          topconValue: 25,
          monopercValue: 25,
          winner: "tie" as const,
        },
      ],
    },
    {
      id: "warranty",
      name: "Warranty & Certification",
      icon: ShieldCheck as LucideIcon,
      parameters: [
        {
          label: "Product Warranty",
          unit: "years",
          topconValue: 12,
          monopercValue: 12,
          winner: "tie" as const,
        },
        {
          label: "Performance Warranty",
          unit: "years",
          topconValue: 30,
          monopercValue: 25,
          winner: "topcon" as const,
        },
        {
          label: "Certifications",
          unit: "",
          topconValue: "IEC 61215, 61730, 62941, BIS, CE",
          monopercValue: "IEC 61215, 61730, 62941, BIS, CE",
          winner: "tie" as const,
        },
      ],
    },
    {
      id: "cost",
      name: "Cost & Value",
      icon: IndianRupee as LucideIcon,
      parameters: [
        {
          label: "Cost Per Watt (est.)",
          unit: "₹/W",
          topconValue: "₹28–30",
          monopercValue: "₹24–26",
          winner: "monoperc" as const,
        },
        {
          label: "LCOE Estimate",
          unit: "₹/kWh",
          topconValue: "₹2.10",
          monopercValue: "₹2.25",
          winner: "topcon" as const,
        },
        {
          label: "Payback Period",
          unit: "years",
          topconValue: "3.8",
          monopercValue: "4.1",
          winner: "topcon" as const,
        },
      ],
    },
    {
      id: "application",
      name: "Application Suitability",
      icon: Target as LucideIcon,
      parameters: [
        {
          label: "Utility-Scale Score",
          unit: "/10",
          topconValue: 9.5,
          monopercValue: 7.5,
          winner: "topcon" as const,
        },
        {
          label: "Commercial Score",
          unit: "/10",
          topconValue: 8.5,
          monopercValue: 8.0,
          winner: "topcon" as const,
        },
        {
          label: "Residential Score",
          unit: "/10",
          topconValue: 7.0,
          monopercValue: 8.5,
          winner: "monoperc" as const,
        },
        {
          label: "Bifacial Gain",
          unit: "%",
          topconValue: 30,
          monopercValue: 20,
          winner: "topcon" as const,
        },
      ],
    },
    {
      id: "environmental",
      name: "Environmental",
      icon: Leaf as LucideIcon,
      parameters: [
        {
          label: "Carbon Footprint",
          unit: "kg CO₂/kW",
          topconValue: 380,
          monopercValue: 410,
          winner: "topcon" as const,
        },
        {
          label: "Recyclability",
          unit: "%",
          topconValue: 92,
          monopercValue: 90,
          winner: "tie" as const,
        },
        {
          label: "Lead-Free",
          unit: "",
          topconValue: "Yes",
          monopercValue: "Yes",
          winner: "tie" as const,
        },
      ],
    },
  ],

  recommendations: [
    {
      useCase: "Best for Utility-Scale",
      winner: "topcon" as const,
      reason:
        "Higher efficiency and lower temperature coefficient deliver superior energy yield in large-scale ground-mount installations where every watt counts.",
      icon: Zap as LucideIcon,
    },
    {
      useCase: "Best for Residential Rooftop",
      winner: "monoperc" as const,
      reason:
        "Lower cost per watt and proven reliability make MonoPERC the practical choice for residential rooftop projects with space constraints and budget sensitivity.",
      icon: Target as LucideIcon,
    },
    {
      useCase: "Best for High-Temperature Climates",
      winner: "topcon" as const,
      reason:
        "With a -0.29%/°C temperature coefficient vs -0.35%/°C, TOPCon retains significantly more power in hot climates — up to 2% more energy yield at 45°C.",
      icon: Thermometer as LucideIcon,
    },
    {
      useCase: "Best for Budget-Conscious Projects",
      winner: "monoperc" as const,
      reason:
        "At ₹24–26/W vs ₹28–30/W, MonoPERC offers 15-20% lower upfront cost while still delivering excellent long-term performance with a 25-year warranty.",
      icon: IndianRupee as LucideIcon,
    },
  ],
};
