export interface GlossaryTerm {
  term: string;
  slug: string;
  category: "Fundamentals" | "Cell Technology" | "Module Technology" | "System Design" | "Policy & Finance" | "Performance";
  definition: string;
  extended?: string;
  relatedTerms?: string[];
  unit?: string;
  range?: string;
}

export const glossaryContent = {
  hero: {
    title: "Solar Energy Glossary",
    subtitle:
      "A comprehensive reference of solar PV terminology — from cell architectures to financing structures. Whether you're new to solar or a seasoned professional, find clear definitions here.",
    backgroundImage: "/assets/home/solar-plant-aerial.webp",
  },

  categories: [
    "Fundamentals",
    "Cell Technology",
    "Module Technology",
    "System Design",
    "Policy & Finance",
    "Performance",
  ] as const,

  terms: [
    { term: "Photovoltaic (PV)", slug: "pv", category: "Fundamentals", definition: "The direct conversion of light (photons) into electricity (voltage) using semiconductor materials.", extended: "First observed by Edmond Becquerel in 1839. Modern PV cells use crystalline silicon to achieve 20-25% conversion efficiency. The photovoltaic effect occurs when photons with energy greater than the bandgap excite electrons across the p-n junction, creating a flow of current.", relatedTerms: ["silicon", "bandgap"] },
    { term: "Kilowatt-Peak (kWp)", slug: "kwp", category: "Fundamentals", definition: "The maximum power output of a solar PV system under Standard Test Conditions (STC: 1000 W/m² irradiance, 25°C cell temperature, AM1.5 spectrum).", unit: "kWp", range: "1 kWp – 10,000+ kWp", relatedTerms: ["stc", "irradiance"] },
    { term: "Irradiance", slug: "irradiance", category: "Fundamentals", definition: "The power of electromagnetic radiation (sunlight) incident on a surface per unit area, measured in W/m².", unit: "W/m²", range: "0 – 1,361 W/m² (solar constant)", extended: "India receives 4-7 kWh/m²/day of global horizontal irradiance, making it one of the best solar resource regions globally." },
    { term: "Standard Test Conditions (STC)", slug: "stc", category: "Fundamentals", definition: "Industry-standard test conditions for rating PV modules: 1000 W/m² irradiance, 25°C cell temperature, Air Mass 1.5 spectrum.", relatedTerms: ["kwp", "nnotc"] },
    { term: "Nominal Operating Cell Temperature (NOCT)", slug: "nnotc", category: "Fundamentals", definition: "The expected cell temperature when operating under: 800 W/m² irradiance, 20°C ambient temperature, 1 m/s wind speed.", unit: "°C", range: "Typically 42-48°C", relatedTerms: ["stc", "thermal-coefficient"] },
    { term: "Silicon (Si)", slug: "silicon", category: "Cell Technology", definition: "The second most abundant element in Earth's crust and the dominant semiconductor material for PV cells. Crystalline silicon (c-Si) accounts for >95% of global PV production.", relatedTerms: ["pv", "monocrystalline"] },
    { term: "Monocrystalline Silicon", slug: "monocrystalline", category: "Cell Technology", definition: "Single-crystal silicon ingot grown via Czochralski process. Higher efficiency (22-26%) than polycrystalline due to uniform crystal structure with no grain boundaries.", relatedTerms: ["polycrystalline", "czochralski"] },
    { term: "Polycrystalline Silicon", slug: "polycrystalline", category: "Cell Technology", definition: "Multi-crystal silicon cast in a quartz crucible. Lower cost than monocrystalline but also lower efficiency (17-20%) due to grain boundary losses.", relatedTerms: ["monocrystalline"] },
    { term: "PERC (Passivated Emitter and Rear Cell)", slug: "perc", category: "Cell Technology", definition: "Cell architecture with a passivated rear surface that reflects unabsorbed light back through the cell for a second pass, boosting efficiency to 23-24%.", extended: "Developed at UNSW in the 1980s, commercialized in the 2010s. The rear passivation layer (typically Al₂O₃/SiNₓ) reduces rear surface recombination by 10-100x vs. standard Al-BSF cells.", relatedTerms: ["topcon", "hjt"] },
    { term: "TOPCon (Tunnel Oxide Passivated Contact)", slug: "topcon", category: "Cell Technology", definition: "N-type cell architecture with ultra-thin tunnel oxide layer and poly-Si passivated contacts. Eliminates direct metal-semiconductor contact, reducing recombination. Efficiencies reach 25-26.5%.", extended: "TOPCon was proposed by Fraunhofer ISE in 2013 and commercialized by JinkoSolar in 2019. The ~1-2 nm SiO₂ tunnel layer allows majority carriers to tunnel through while blocking minority carriers, enabling full-area passivated contacts without patterning.", relatedTerms: ["perc", "hjt", "n-type"] },
    { term: "HJT (Heterojunction Technology)", slug: "hjt", category: "Cell Technology", definition: "Cell architecture combining crystalline Si wafer with amorphous Si thin-film layers. Symmetric structure with intrinsic a-Si buffer layers. Potentially 27%+ efficient.", extended: "Sanyo (now Panasonic) pioneered HJT with their HIT cells. Advantages: excellent temperature coefficient (-0.26%/°C), high bifaciality (>90%), simple low-temperature processing (<200°C). Challenge: high cost of indium tin oxide (ITO) transparent conductor.", relatedTerms: ["topcon", "perc"] },
    { term: "N-type Silicon", slug: "n-type", category: "Cell Technology", definition: "Silicon doped with phosphorus (5 valence electrons vs. Si's 4) providing excess electrons as majority carriers. Less prone to Light-Induced Degradation (LID) than p-type.", extended: "N-type wafers are the industry's future direction — all TOPCon and HJT cells use n-type. Adani Solar's 4 GW TOPCon line uses n-type Czochralski wafers.", relatedTerms: ["p-type", "topcon"] },
    { term: "P-type Silicon", slug: "p-type", category: "Cell Technology", definition: "Silicon doped with boron (3 valence electrons) creating holes as majority carriers. Susceptible to boron-oxygen LID (1-3% initial degradation). Historically dominant in PERC.", relatedTerms: ["n-type", "perc"] },
    { term: "Bifacial Module", slug: "bifacial", category: "Module Technology", definition: "PV module that generates power from both front and rear sides. Rear-side gain depends on ground albedo and mounting height: 5-30% additional yield vs. monofacial.", extended: "Bifaciality factor = rear-side efficiency / front-side efficiency. TOPCon bifaciality: 80-85%. HJT: 90-95%. Best with single-axis trackers or high-clearance fixed-tilt systems over reflective surfaces (white TPO, sand, snow).", relatedTerms: ["topcon", "albedo"] },
    { term: "Half-Cut Cells", slug: "half-cut", category: "Module Technology", definition: "Solar cells cut in half to reduce current by 50% and resistive (I²R) losses by 75%. Also improves shade tolerance since each half operates more independently.", relatedTerms: ["mbb"] },
    { term: "Multi Busbar (MBB)", slug: "mbb", category: "Module Technology", definition: "Interconnection technology using 9-16 thin busbars (vs. traditional 4-5) to reduce finger length, lower series resistance, and improve shade tolerance. Also reduces silver paste consumption.", relatedTerms: ["half-cut"] },
    { term: "Encapsulant (EVA/POE)", slug: "encapsulant", category: "Module Technology", definition: "Polymer layer that laminates cells between front glass and rear backsheet/glass. EVA (Ethylene Vinyl Acetate) is standard; POE (Polyolefin Elastomer) is preferred for bifacial/glass-glass modules due to lower PID susceptibility and better moisture resistance.", relatedTerms: ["pid"] },
    { term: "Inverter", slug: "inverter", category: "System Design", definition: "Device that converts DC output from solar modules to AC for grid connection or local consumption. String inverters (centralized), microinverters (per-module), and hybrid inverters (with battery) are common types.", extended: "Modern string inverters achieve 98-99% efficiency with MPPT tracking. For utility-scale, central inverters (1-5 MW per unit) are most cost-effective. For residential, microinverters (Enphase, SolarEdge) optimize per-panel output." },
    { term: "Net Metering", slug: "net-metering", category: "Policy & Finance", definition: "Policy allowing solar system owners to export excess generation to the grid and receive credit on their electricity bill at or near retail tariff rate.", extended: "India's net metering policies vary by state: most allow up to 100% of sanctioned load, export rate = APPC (~₹3-4/kWh) or retail tariff (~₹8/kWh) depending on state. Key states: Maharashtra, Karnataka, Tamil Nadu have favorable policies." },
    { term: "Levelized Cost of Energy (LCOE)", slug: "lcoe", category: "Policy & Finance", definition: "The total lifecycle cost of a solar system divided by total lifetime energy output, expressed in ₹/kWh or $/kWh.", unit: "₹/kWh", range: "₹1.5 – ₹4/kWh (utility-scale India)", extended: "LCOE = (CAPEX + Σ OPEX / (1+r)^t) / Σ E_t / (1+r)^t. Indian utility-scale solar LCOE has dropped from ₹15/kWh in 2010 to ₹2-3/kWh in 2025, making solar the cheapest new electricity source." },
    { term: "Accelerated Depreciation", slug: "accelerated-depreciation", category: "Policy & Finance", definition: "Tax benefit allowing 40% depreciation per year on solar assets (vs. standard 5-15% for other assets). Reduces taxable income significantly in first 3 years, improving project IRR by 2-4%.", extended: "India's Income Tax Act Section 32 allows accelerated depreciation for renewable energy assets. Combined with 10-year tax holiday under Section 80-IA, solar projects can achieve effective tax rates of 5-10% in early years." },
    { term: "Performance Ratio (PR)", slug: "performance-ratio", category: "Performance", definition: "Ratio of actual AC energy output to theoretical DC output if the system operated at STC for all hours of irradiance. Accounts for all system losses.", unit: "%", range: "70-85% (good), 80-90% (excellent)", extended: "PR = E_actual / (P_nominal × ΣG_incident / G_STC). Typical loss components: inverter (2-3%), soiling (2-5%), temperature (5-15%), shading (1-10%), mismatch (1-2%), cables (1-2%)." },
    { term: "Capacity Utilization Factor (CUF)", slug: "cuf", category: "Performance", definition: "Ratio of actual annual energy output to maximum possible output if the plant operated at full rated capacity 24/7/365.", unit: "%", range: "15-25% (fixed-tilt India), 20-30% (tracker India)", extended: "CUF = E_annual / (P_nominal × 8760). In India, typical CUF is 17-20% for fixed-tilt and 22-28% for single-axis tracker systems. Adani Solar's Mundra reference plant achieves 19.5% CUF." },
    { term: "Temperature Coefficient", slug: "thermal-coefficient", category: "Performance", definition: "Rate of power output decrease per degree above STC (25°C). Crystalline Si: -0.30 to -0.45%/°C. TOPCon: -0.30%/°C. HJT: -0.26%/°C (best in class).", unit: "%/°C", extended: "At 45°C ambient (common in Rajasthan), cell temperature reaches ~65°C, causing 12-18% power derating for PERC vs. 10-12% for TOPCon and 8-10% for HJT. This is why HJT/TOPCon outperform in hot climates." },
    { term: "PID (Potential Induced Degradation)", slug: "pid", category: "Performance", definition: "Power loss caused by voltage-driven ion migration between cells and frame/glass, especially in hot/humid conditions. Can cause 10-30% degradation if untreated.", extended: "Anti-PID measures: use POE encapsulant, grounded negative pole, anti-PID modules (with PID-resistant cells and encapsulants). Adani Solar modules are PID-resistant to IEC 62804 (<2% power loss after 192h test)." },
    { term: "Albedo", slug: "albedo", category: "Performance", definition: "The reflectivity of the ground surface beneath/behind a bifacial installation. Higher albedo = more rear-side irradiance = more bifacial gain.", range: "0.05 (dark soil) – 0.85 (fresh snow)", extended: "Typical values: grass (0.20), concrete (0.30), white TPO membrane (0.60-0.80), sand (0.40), water (0.06). White TPO roofs are excellent for bifacial rooftop systems." },
  ] as GlossaryTerm[],
};
